// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/service-page/AccessibilityFirst.tsx": () => import("../components/mockups/service-page/AccessibilityFirst.tsx"),
  "./components/mockups/service-page/AffordanceStrong.tsx": () => import("../components/mockups/service-page/AffordanceStrong.tsx"),
  "./components/mockups/service-page/HierarchyClear.tsx": () => import("../components/mockups/service-page/HierarchyClear.tsx")
};
